---
- block:
    - name: install lvs
      apt: name=ipvsadm=1:1.26-4 state=present
      tags: install_ipvsadm

    - name: install keepalived
      apt: name=keepalived=1:1.2.13-1 state=present
      tags: install_keepalived

    - name: config keepalived
      template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
      tags: keepalived.conf
    
    - name: config keepalived.conf to nginx
      template: src=keepalived.conf.nginx.j2 dest=/etc/keepalived/keepalived.conf.nginx
      tags: keepalived.conf.nginx
    
    - name: confige realserver shell
      template: src=lvs_realserver.sh.j2 dest=/etc/init.d/lvs_realserver.sh mode=0755
      tags: lvs_realserver.sh

    - name: confige realserver shell pwoer on automatically.  tags --> exec_boot
      shell: grep lvs_realserver.sh /etc/rc.local || sed -i '/^exit/ i/etc/init.d/lvs_realserver.sh start' /etc/rc.local
      tags: exec_boot

  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"
